### ISSUE TITLE
Allow book info to include links to personal servers for file sharing

### ISSUE THREAD

**Issue by andpersand** [bookwyrm-social/bookwyrm#97] opened 2020-03-25 18:29 UTC
It might be useful to have some way for users to find a link to download ebook, audiobook, or PDF files. This could also allow people to more easily share zines and community-made things that might be difficult to find otherwise.

**Comment by mouse-reeve** [comment] 2020-03-25 19:30
Yes! thank you!

I think this is related to but not a duplicate of #57, wrt integrating with overdriver, openlibrary loans, and internet archive ebooks

**Comment by mouse-reeve** [comment] 2020-03-25 19:32
also related to #54

**Closed** 2022-01-13 19:10 UTC
Labels: enhancement, good first issue, books
