### ISSUE TITLE
Merge individual book entries to editions of one and the same book entry

### ISSUE THREAD

**Issue by Cs137** [bookwyrm-social/bookwyrm#2307] opened 2022-10-02 15:01 UTC
**Is your feature request related to a problem? Please describe.**
Since many books are existing a couple of times, it would be handy to merge them to one entry and define them as new editions.

**Describe the solution you'd like**
Option to search for book within entry editor and checkbox to define currently editing entry as version of book found via the onpage search.

**Comment by nichobi** [comment] 2022-11-07 10:30
Duplicate of #562 (though the title is a little hard to search for)

**Comment by mouse-reeve** [comment] 2023-02-18 03:31
Closing this as a duplicate of #2664

**Closed by mouse-reeve** 2023-02-18 03:31 UTC
