### ISSUE TITLE
Missing formats

### ISSUE THREAD

**Issue by lisbonjoker** [bookwyrm-social/bookwyrm#1758] opened 2022-01-04 13:36 UTC
Add Manga and Light novel to Format.
[![https://imgur.com/UeMLDz2.png](https://imgur.com/UeMLDz2.png)](https://imgur.com/UeMLDz2.png)

**Comment by mouse-reeve** [comment] 2022-01-11 19:39
(copied from Matrix): As I recall, the list was added the way it is to fit a metadata standard, which is why it's so short. The idea was that more nuanced types, like manga and light novel, would be added as "format details" (which is displayed instead of the format when it's present). But it's worth re-evaluating that, or at least being more clear about what metadata standard is being met.

**Comment by mouse-reeve** [comment] 2023-08-07 01:42
I did a little digging and the (short) list of formats is from https://schema.org/BookFormatType. In my view, this issue would be resolved by making it clearer that `format details` is meant to be a place to add in more nuanced types, which is addressed in https://github.com/bookwyrm-social/bookwyrm/issues/2840

I'm going to close this as a duplicate of the above issue

**Closed by mouse-reeve** 2023-08-07 01:42 UTC
