### ISSUE TITLE
Import failed

### ISSUE THREAD

**Issue by DougNix** [bookwyrm-social/bookwyrm#2579] opened 2023-01-07 21:33 UTC
I tried importing a list of books but all of the items failed. It's not clear to me why they failed, as the titles, authors, and ISBNs all resolved. Can you have a look to see what needs done to resolve the problem?

**Comment by mouse-reeve** [comment] 2023-01-07 22:28
Dang, I'm sorry to hear it totally failed to import anything! Would you be comfortable attaching the CSV file you used for the import? Also, what mode (like, Goodreads or Storygraph, etc) were you using?

**Comment by DougNix** [comment] 2023-01-09 16:18
Hey Mouse,

Here’s the file.
￼
--
Doug Nix
***@***.***

(519) 729-5704

"The important thing is not to stop questioning. Curiosity has its own reason for existing." Albert Einstein

**Comment by mouse-reeve** [comment] 2023-01-11 16:07
It looks like the file didn't attach properly, can you try again directly from the github UI rather than via email?

**Comment by DougNix** [comment] 2023-01-13 15:40
Hi Mouse,
Here's the file again.
[libbytag-🧾---titles.csv](https://github.com/bookwyrm-social/bookwyrm/files/10412982/libbytag-.---titles.csv)

**Comment by DougNix** [comment] 2023-02-01 13:18
Perhaps having a template CSV file available would allow a user to create a correct file from data coming from an app not directly supported.

**Comment by mouse-reeve** [comment] 2023-02-20 19:39
Yes, since this isn't a format we currently support, I think this is a duplicate of #2411. Thank you all!

**Closed by mouse-reeve** 2023-02-20 19:39 UTC
Labels: feature: csv imports
