### ISSUE TITLE
Site is Incredibly Slow/Prone to Downtime

### ISSUE THREAD

**Issue by TomatDividedBy0** [bookwyrm-social/bookwyrm#2357] opened 2022-11-13 21:51 UTC
This has been an issue since I first started using the site years ago, and some friends I've reccommended it to complain about it too. The site is prone to unreasonably long loading times and whether or not you actually get a response or some sort of HTTP error is also a tossup. If the site takes nearly a minute to load a page and is frequently plagued with downtime, that's going to seriously repel users. 

Any idea what structually might be causing this? I remember discussing this on the Matrix a year or so back, what I heard was that it had to do with either Python or the database system scaling poorly performance-wise (my memory is foggy, however). It might be worth discussing the causes and how to lay the groundwork for fixing the problem if it's something inherent to the code/application itself.

**Comment by hughrun** [comment] 2022-11-14 03:02
This is being discussed. If you would like to help and have any specific suggestions please join the Matrix chat.

It's likely to be primarily due to inefficient database calls and task queueing. The last two weeks has certainly been a stress test for the entire fediverse.

**Comment by mouse-reeve** [comment] 2022-11-14 17:29
Yep! It's very real and I super appreciate how generous everyone has been with me with the process of trying to get things stable again.

**Comment by marcusyoung** [comment] 2022-11-15 00:19
Pulling up profile and feed seem particular slow, even when there is no activity on the server and very little data (I've only just set the server up). Both push a CPU core up to 100% for a moment or two. Pulling other stuff up like books is much snappier.

**Comment by mouse-reeve** [comment] 2022-11-15 00:49
I believe those two pages' slowness is caused by expensive database queries. A while back I added some query caching, but that hasn't provided substantial improvement. There may still be some low-hanging fruit that would be easy to fix on those pages, and there's a branch with [Django debug toolbar](https://github.com/bookwyrm-social/bookwyrm/tree/debug-toolbar) that I've been using intermittently to try and diagnose that.

I've been adjusting the celery settings and nginx rate limiting as well, and I'm feeling tentatively hopeful with that. I've also been working on improving performance and reducing the frequency of common celery tasks.

**Comment by marcusyoung** [comment] 2022-11-15 01:57
If you can share the SQL queries behind those two pages I wouldn't mind taking a look at how they perform directly on my database and look for possible optimization.

**Comment by mouse-reeve** [comment] 2022-11-16 05:08
Some related PRs:
#2385 #2384 #2380 #2346

**Comment by marcusyoung** [comment] 2022-11-16 20:05
> Some related PRs:
> #2385 #2384 #2380 #2346

Thanks. Not sure I can help much then as it's a Django library which is generating the SQL queries. I wonder to what extent it optimises for the different DBMS it supports or just goes for something generic that will work for all but which might not be optimal. While I know SQL pretty well, I know nothing about Django and little Python. ☹️

**Comment by WesleyAC** [comment] 2023-03-13 05:40
#2726 and #2723 should significantly improve how quickly the task queue gets processed.

Beyond that, I think a lot of the 500 errors and timeouts are caused by a poor default gunicorn configuration (see #2731 and #2717 for some info on that). I have a relatively good configuration on bookwyrm.social right now, and I hope to get more reasonable defaults and maybe some documentation on tuning merged at some point, but in the meantime, if any other server admins want tuning advice, feel free to reach out.

The Django ORM does make debugging SQL queries a little tricky, but what I've found works well is just printing out the `.query` property of the `QuerySet`, then pasting that into postgres `EXPLAIN`. I think a pretty frequent problem is accidentally joining together tables in ways that prevent postgres from being able to effectively use the indexes it has. It can be hard to figure out how to coerce Django into generating the more efficient SQL, if anyone has advice on that I'd be happy to hear it, it's mostly been trial and error for me.

**Comment by WesleyAC** [comment] 2023-03-21 01:11
I'm going to go ahead and close this, since I think it's been significantly improved by the gunicorn changes on bookwyrm.social (monitoring reports a average response time of 702 ms, which is on the high end but reasonable on the whole). There's still a lot that can be improved in terms of performance optimizations, but I think things are in a pretty stable configuration right now.

If there are any pages that seem particularly slow, please do open issues for those individually, and I can look into optimizing them.

**Closed by WesleyAC** 2023-03-21 01:11 UTC
Labels: bug
