### ISSUE TITLE
Add illustrator field for books

### ISSUE THREAD

**Issue by andpersand** [bookwyrm-social/bookwyrm#1944] opened 2022-02-13 18:33 UTC
Occasionally I run into a book on bookwyrm that has an illustrator. In order to credit the illustrator and allow people to search for an illustrator they like, I'll often include the illustrator as a secondary author. However, this isn't ideal and could be confusing. I would love to see an optional "illustrator" field alongside the "author" field.

This could either work exactly as the author field does but with an "Illustrator" label, or it could be implemented as a drop-down label selection for new authors/contributors. This second option might also be helpful for editors, essayists, or people who have contributed a foreword. 

An example of a book with an illustrator listed as an author is [Plain Bad Heroines](https://bookwyrm.social/book/95045), where [Emily M. Danforth](https://bookwyrm.social/author/12944) is the author and [Sara Lautman](https://bookwyrm.social/author/12945) is the illustrator.

**Comment by mouse-reeve** [comment] 2022-02-15 19:29
Yes! This is closely related to #1120

**Comment by mouse-reeve** [comment] 2023-08-07 01:56
I'm closing this as a dupe of #1120

**Closed by mouse-reeve** 2023-08-07 01:56 UTC
