### ISSUE TITLE
Import via individual csv and cover from URL

### ISSUE THREAD

**Issue by michael-koschorreck** [bookwyrm-social/bookwyrm#2553] opened 2022-12-27 20:57 UTC
I have a database with a larger collection of books I would like to import. I would like to avoid the detour via Goodreads etc. Also, many of my books are not available there. I would also like to import the covers via a URl. Is there documentation on which fields must be present in the CSV for upload? And does the feature "cover from URL" also work in CSV import? Creating the books individually is too lavish for me.

**Comment by mouse-reeve** [comment] 2023-01-11 15:47
The CSV import tool doesn't actually use the data in the CSV file to _create_ books, rather, it uses it to look up books in the local database and other external databases (OpenLibrary, Inventaire, and other bookwyrm instances). This is because generally those CSV files don't provide enough metadata to create a meaningful book entry, and because it would be very easy to accidentally create thousands of books with garbled data.

I'm not sure what the best solution is here, to be honest! I know a lot of users like you who have lists of books that don't have good coverage in existing databases are frustrated with how labor intensive it would be to add those books individually, but alternatives would need to be very carefully built.

**Comment by mouse-reeve** [comment] 2023-01-11 16:22
After having done some poking around in the issue, queue, I'm going to close this as a duplicate of #2354

**Closed by mouse-reeve** 2023-01-11 16:22 UTC
Labels: feature: csv imports
