### ISSUE TITLE
Followers-only replies to followers-only posts should not appear in the home feed if you do not follow the person the post was a reply to

### ISSUE THREAD

**Issue by bcj** [bookwyrm-social/bookwyrm#1870] opened 2022-01-25 20:40 UTC
**Describe the bug**
This one is skirting the line between bug report and feature request. The most direct bug is: If someone you don't follow makes a followers-only post, and someone you do follow replies, the reply will appear in your feed but the 'status' (or other post type) link will take you to a 404 page.

Personally, I would consider it a bug if a reply to a followers-only post appears on my timeline if I don't follow everyone involved because it seems like it would be a faux pas to interact with that post but that is definitely more subjective and posts having different visibility makes that complicated. If pressed I would argue:

| original post | reply | visible | notes |
| ------------ | ----- | ------ | ------ |
| public           | public | If I follow replier or reply is boosted | also would be fine with "if I follow both" but that's a bigger change and not in line with mastodon |
| public     | followers-only | If I follow replier | see above |
| followers-only | public | If I follow replier or reply is boosted | kind of think this shouldn't be allowed but that's a fediverse complaint |
| followers-only | followers-only | If I follow both | |

The above is definitely subjective, so mostly putting out feelers on whether it makes sense as a feature request to be made on how the home feed displays, a feature request for filters (e.g., Add a 'Hide replies to accounts you don't follow' Checkbox to Filters) or just undesired behavior

**To Reproduce**
1. Create a followers-only status with account A, which account C doesn't follow
2. Reply to that status with account B, which account C does follow
3. Find the reply in account C's feed and click on the 'status' link in the header 'Account B replied to Account A's status'
4. View 404 page

**Expected behavior**

One of:
• reply not in feed in the first place
• 'status' not presented as a link
• 403 instead of 404 (I guess that would imply that any link of the form `SITE/user/USER@SITE/POSTTYPE/ID` should be a 403 if you don't follow user/aren't logged in. Hmm)

**Screenshots**
N/A

**Instance**
bookwyrm.social

**Additional context**

Sorry, this is a ramble-y/subjective bug

---

**Desktop (please complete the following information):**
    - OS: macOS
    - Browser Firefox
    - Version 97.0b7

**Comment by quaayd** [comment] 2022-01-26 07:51
This kind of bothers me too. if i click on a comment that is a response to someone i don't follow, I get a "Not Found, the page you requested doesn't seem to exist", which feels like gaslighting, tbh. the page exists, i'm just not able to access it.

**Comment by mouse-reeve** [comment] 2022-01-26 16:14
That's definitely unexpected behavior - either you should be able to see something or not. When you try to access a page that you don't have permission to view, it makes more sense on a strictly technical level to produce a `PermissionDenied` error, but I've been using 404s because it gives more privacy to the hidden content by providing less information to the user trying to view it. I believe that's a fairly common pattern for that situation.

**Comment by hughrun** [comment] 2022-08-14 04:02
I think I have a potential fix for this. Stay tuned.

**Comment by hughrun** [comment] 2022-08-28 10:15
@mouse-reeve can this be closed now, or are you waiting for a release?

**Comment by mouse-reeve** [comment] 2022-08-28 13:45
Oh! It can be closed, I thought it would have closed automatically

**Closed by mouse-reeve** 2022-08-28 13:45 UTC
Labels: bug
