### ISSUE TITLE
Search My Shelves

### ISSUE THREAD

**Issue by varanasib** [bookwyrm-social/bookwyrm#2673] opened 2023-02-16 19:51 UTC
**Is your feature request related to a problem? Please describe.**
A search for a title or author returns possibly relevant books, sometimes more than one of the same book.  Yet, the search results do not indicate if I have it on any of my shelves.

**Describe the solution you'd like**
I would like to see an indication of which of my shelves a book is on, or that the book is not on any of my shelves.

**Describe alternatives you've considered**
I click on the book and look for whether I have any reading history.  (I think "reading history" really means whether I have shelved the book or not.)

**Comment by chdorner** [comment] 2023-02-17 10:41
I'd say this is a duplicate of #2079 which already has somebody working on it 😄

**Closed by chdorner** 2023-02-17 10:41 UTC
