### ISSUE TITLE
A more flexible way to add dates

### ISSUE THREAD

**Issue by miguelmaiquez** [bookwyrm-social/bookwyrm#2872] opened 2023-06-15 18:53 UTC
The current calendar system for adding the 'finished date' of a read book only allows to add exact dates (YY/MM/DD), but we often remember only the year we finished reading a book, not the day and the month, especially if it was long ago.

Same problem with publication dates, since usually only the year (sometimes also the month) is known, but not the day.

This could be solved allowing the month and/or day to be left blank (YY/--/--).

**Comment by mouse-reeve** [comment] 2023-07-16 00:40
Big agree! This is a duplicate of #743 so please subscribe to that ticket

**Closed by mouse-reeve** 2023-07-16 00:40 UTC
