### ISSUE TITLE
Searching for between the world and me returns 502 or 504

### ISSUE THREAD

**Issue by treaz** [bookwyrm-social/bookwyrm#1895] opened 2022-02-01 12:56 UTC
**Describe the bug**
Search for the book "between the world and me" returns get a 502/504 nginx error page

**To Reproduce**
1. Go to https://bookwyrm.social/search?q=Between+the+World+and+Me
2. See error

**Expected behavior**
No error :)
At the same time, other search queries run ok...

**Instance**
bookwyrm.social

**Additional context**
is there an unsanitized query that goes directly to the DB???

**Comment by cincodenada** [comment] 2022-02-01 21:24
Well dang, it sure does! Thanks for reporting!

I don't have an exhaustive knowledge of the codebase but we use the ORM pretty heavily, so I would be surprised if a simple search like this was making it into the query, but you're right that the title being similar to an SQL condition is suspicious! I was able to reproduce with that search on my own instance, which indicates that it's probably not a data issue, even.

After digging in a bit, the logs pointed at some performance monitoring we're doing, and indeed disabling that seems to have fixed the crash, which is unexpected.

Specifically for others running things, I commented out the `OTEL_*` variables in my `.env` and ran `./bw-dev up -d web` to restart things, and now a search for that book works.

So, still some digging to do as to _why_ that's crashing things, because it definitely shouldln't be, and maybe a bug to file upstream somewhere, but disabling the OTEL seems to be a workaround for now. I'm not sure who else is using the OTEL exporters other than me and @mouse-reeve - they're pretty new.

**Comment by mouse-reeve** [comment] 2022-02-01 21:43
This looks more like a timeout to me than an error -- I wonder if changing the OTEL configuration is tipping the query over the edge of taking too long, rather than introducing a bug itself? I was able to execute this query without issue on my test instance. And it does use the ORM, so it's not likely to be executing any strings directly. 

I think there's a couple things at play: first, searching the local database doesn't always rank results as well as it ought to, so a match doesn't come up when you expect it to, or the match isn't the best available match. Second, and more importantly, searching external sources is taking too long, which causes the error state. That can be configured to some degree on an instance-by-instance level (#1780) and by changing connector priority, but I'd like to also address it more head-on in how the view approaches making potentially slow external http requests.

That could mean executing the requests in parallel and then returning whichever queries produce results in the available timeout period, rather than looping through a prioritized list of connectors.

**Comment by mouse-reeve** [comment] 2022-05-31 17:51
I believe this is fixed by #2139 but feel free to re-open if problems persist

**Closed by mouse-reeve** 2022-05-31 17:51 UTC
Labels: bug, feature: search
