### ISSUE TITLE
Feature "Narrator" info for Audiobooks

### ISSUE THREAD

**Issue by FluffyCowBird** [bookwyrm-social/bookwyrm#2569] opened 2023-01-03 03:33 UTC
I hate to say it, but I mostly read audiobooks these days.

So, it would be amazing if Bookwyrm offered the ability to list Narrators for each audiobook.

It would be best if there were opportunities for multiple narrators, as many books have two or more readers featured.

**Comment by mouse-reeve** [comment] 2023-02-20 19:32
I agree! I'm closing this as a duplicate of #1120, and you can follow that one if you'd like progress updates, but you're quite right and thank you for opening an issue.

**Closed by mouse-reeve** 2023-02-20 19:32 UTC
