### ISSUE TITLE
Additional metadata field for translator(s) in book entry

### ISSUE THREAD

**Issue by Cs137** [bookwyrm-social/bookwyrm#2308] opened 2022-10-02 15:03 UTC
**Is your feature request related to a problem? Please describe.**
For translated version of books, it would be handy to assign translator(s) to the entry.

**Describe the solution you'd like**
List of objects comparable to the author(s).

**Comment by franbarra** [comment] 2022-10-03 19:07
Hello! This issue of multiple types of authors was discussed in #1120.

**Comment by mouse-reeve** [comment] 2022-11-25 17:23
Closing this as a duplicate of #1120 ❤️

**Closed by mouse-reeve** 2022-11-25 17:23 UTC
