### ISSUE TITLE
Cannot follow my new account from Mastodon

### ISSUE THREAD

**Issue by xaviershay** [bookwyrm-social/bookwyrm#2545] opened 2022-12-26 09:43 UTC
I'm seeing the exact same issue as #1928 using https://mas.to (of which I am just a user, not an admin), but I suspect might be a different cause.

**Describe the bug**

Following my account with my mas.to account leads to a pending approval request. My account is not set to moderate follow requests, nor do I see any request in my account profile.

**To Reproduce**

* Try to follow @xavier@bookwyrm.social from [mas.to](https://mas.to/)

**Expected behavior**

Account is followed with no pending approval.

**Instance**

bookwork.social

**Additional context**

* Following [@followTest@wyrms.de](http://wyrms.de/user/followTest) works as expected.
* My eyes don't detect any significant differences between [my JSON](https://bookwyrm.social/user/xavier.json) and followTest.
  
Sorry I'm too new to this whole thing to know how debug more effectively, but am happy to chase down leads. I don't _really_ need this feature, I was mostly curious whether it would be a good option for publishing a feed to mastodon.

Thanks for all your work 🙏

**Comment by weijia-cheng** [comment] 2022-12-26 17:18
I am also having this problem trying to follow `@weijia_sophia_cheng@bookwyrm.social` from `@weijia_sophia_cheng@deacon.social`. Same issue with the pending approval request.

**Comment by weijia-cheng** [comment] 2022-12-26 17:21
What I see right after I click "follow" from `deacon.social`:

![Screenshot from 2022-12-26 09-20-13](https://user-images.githubusercontent.com/1240463/209571264-6a31e3df-5c76-4eb5-9656-a22e81b4dd2c.png)

What happens shortly after I refresh the page:

![Screenshot from 2022-12-26 09-20-23](https://user-images.githubusercontent.com/1240463/209571302-c7907882-0aa9-4726-913f-57d520c9bab1.png)

**Comment by xaviershay** [comment] 2022-12-26 19:40
Confirming that those screenshots match my experience, and I get the same behaviour attempting to follow `@weijia_sophia_cheng@bookwyrm.social`.

**Comment by marcusyoung** [comment] 2022-12-27 14:49
In my experience this will resolve itself in a day or two. It appears to be caused by a backlog of tasks on the bookwyrm.social instance.

**Comment by weijia-cheng** [comment] 2022-12-29 23:04
@marcusyoung You're right, it did resolve itself a little afterwards.

**Comment by fasiha** [comment] 2023-01-01 01:21
Hmm, the issue hasn’t resolved for me for several weeks, but will try to toggle “withdraw” and “follow” again now and check in a couple of days.

**Comment by quisquous** [comment] 2023-01-01 20:34
> Hmm, the issue hasn’t resolved for me for several weeks, but will try to toggle “withdraw” and “follow” again now and check in a couple of days.

Depending on your server, it could also be #1179.

**Comment by asmaloney** [comment] 2023-01-05 03:15
Just a "me too" - I'm trying to follow from fosstodon.org.

How do I know if they have "secure mode" on?

**Comment by marcusyoung** [comment] 2023-01-05 08:45
Allow up to 48 hours for this to take effect if you are on bookwyrm.social. This is caused by a backlog of background tasks due to the number of users on that instance.

**Comment by asmaloney** [comment] 2023-01-05 12:21
OK thank you. Is scaling problem being tracked somewhere? It's a logical "first thing" to do, so it's a little confusing and detracts from the UX.

**Comment by marcusyoung** [comment] 2023-01-05 13:12
I don't know if it's a scaling problem or just inadequate resource. I don't know what spec bookwyrm.social is running.

**Comment by hughrun** [comment] 2023-01-20 09:40
bookwyrm.social has had some issues with Celery (task manager) falling over in recent times, which can cause delays like this. There is a fix coming soon to deal with `AUTHORIZED_FETCH` (secure mode) Mastodon servers.

**Comment by mouse-reeve** [comment] 2023-01-26 16:53
For bookwyrm.social users, this should now be taking a couple minutes tops, rather than days or hours. If you have a pending follow request, try cancelling a pending follow request and re-following the user. Please let me know if the follow doesn't go through within maybe 5 minutes.

I think it may be possible to have some of these transactions happen synchronously when there aren't external requests that need to be made (ie, if the remote user in the relationship is already known to the local server), which would be a big improvement as well.

**Comment by mouse-reeve** [comment] 2023-02-20 19:14
I'm going to close this on the assumption that follow requests are no longer problematic. Please open a new issue if they are, because it's probably a new problem. I extremely appreciate you all bearing with me on this one!

**Closed by mouse-reeve** 2023-02-20 19:14 UTC
Labels: bug
