### ISSUE TITLE
There appears to be an unspecified size limit on profile pictures

### ISSUE THREAD

**Issue by eldang** [bookwyrm-social/bookwyrm#344] opened 2020-11-12 16:09 UTC
**Describe the bug**
Trying to upload a 2.6MB profile picture gets a 413 error, with no feedback about how large "too large" is.  A 782kb image works, so somewhere between those sizes there appears to be a cutoff which the UI should warn users about.

**To Reproduce**
1. Go to 'https://bookwyrm.social/user-edit/
2. Browse for a large profile picture
3. Click "save"; get 413 error.

**Expected behavior**
Either the profile picture uploads, or there's a message saying that it's too large and spelling out what the file requirements are.

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.15.7
 - Browser Firefox
 - Version 82.0.2

**Comment by mouse-reeve** [comment] 2020-11-12 19:44
oddly enough, I don't think this is explicitly defined anywhere. It may be coming from django or from pillow?

**Comment by eatsleepdeploy** [comment] 2021-05-18 14:27
I think the issue is `client_max_body_size` in nginx. Tested locally by uploading a 3.7MB file & failing, then setting `client_max_body_size=10m;` in the nginx conf and retrying and the file uploads successfully. And the default size is [1m](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size), so makes sense.

I can see a couple of solutions:

1. Change the post to AJAX somehow and handle 413 by showing an error (more performant but not sure if hard w/ current FE, not looked at it yet).
2. Up the Nginx limit to something big (and hope no-one tries to upload a file that big), and instead set a limit on the `EditUserForm` or something to return a sensible error if it's over say 5Mb?
3. Some other solution? 😄 

Also, it doesn't look like the nginx config is in the repo so guessing can't do that bit in an MR?

**Comment by mouse-reeve** [comment] 2021-05-18 16:29
Thank you! It didn't occur to me that nginx would be the issue here. The nginx config is part of the repo - there are versions for prod and development: https://github.com/bookwyrm-social/bookwyrm/tree/main/nginx

**Comment by eatsleepdeploy** [comment] 2021-05-19 00:26
Aaaaah, OK in that case I'll see if I can get an MR together and pick a solution above.

**Comment by mouse-reeve** [comment] 2021-05-19 01:03
Great! The images are being resized after upload, but I think it's sensible to have a limit on upload size as long as it's communicated clearly

**Comment by mouse-reeve** [comment] 2021-06-01 21:12
Fixed by #1123

**Closed by mouse-reeve** 2021-06-01 21:12 UTC
Labels: bug, good first issue

**Comment by eldang** [comment] 2021-06-01 22:20
Yay!  Thank you @eatsleepdeploy
