### ISSUE TITLE
Weird CSS issue 

### ISSUE THREAD

**Issue by bibliotechy** [bookwyrm-social/bookwyrm#1159] opened 2021-06-04 22:55 UTC
Text of some posts in feed is offset in a weird way on mobile device

**To Reproduce**
1. Go to feed item for “28 Days later” in mobile view

**Expected behavior**
Body of feed item should not be offset

**Screenshots**
![Weird text bookwyrm](https://user-images.githubusercontent.com/1128631/120870162-31eec600-c566-11eb-9c02-18c80200864d.png)

**Smartphone (please complete the following information):**
    - Device: iPhone 11 Pro
    - OS: latest
    - Browser: safari and Firefox 
    - Version latest

**Comment by mouse-reeve** [comment] 2021-06-04 23:01
yeah this is totally janky! It happens when there should be a book cover, but it doesn't load for whatever reason. I'm closing this issue as a duplicate of https://github.com/bookwyrm-social/bookwyrm/issues/1073, but thank you for pointing it out!

**Closed by mouse-reeve** 2021-06-04 23:01 UTC
