### ISSUE TITLE
Allow "Manually add book" when importing from Goodreads

### ISSUE THREAD

**Issue by dancst** [bookwyrm-social/bookwyrm#2880] opened 2023-06-22 17:48 UTC
Many books don't have a match when importing from Goodreads .cvs file. 
Maybe an option for adding the book as a new book, like in the "manually add book" option, could be a solution. 

More context: I have been using Goodreads for many years, adding new books that I have read but don't exist on Goodreads database (books edited in spanish or portuguese, or by small editors and very rare), obviously, those books aren't in the bookwyrm database neither.

**Comment by mouse-reeve** [comment] 2023-08-07 02:00
Closing this as a duplicate of https://github.com/bookwyrm-social/bookwyrm/issues/1820, which has a bit more context on the way forward

**Closed by mouse-reeve** 2023-08-07 02:00 UTC
