### ISSUE TITLE
bw-dev update fails with "Invalid value set for option Signed-By regarding" nodesource

### ISSUE THREAD

**Issue by nesges** [bookwyrm-social/bookwyrm#3190] opened 2024-01-03 19:30 UTC
**Describe the bug**
When updating from v0.6.6 to v0.7.1 `docker-compose build` fails with the following error:
```
 => ERROR [6/7] RUN apt-get update            &&     apt-get install -y nodejs &&     pip install -r requirements.txt &&     npm install .                                                                                              0.5s
------
 > [6/7] RUN apt-get update            &&     apt-get install -y nodejs &&     pip install -r requirements.txt &&     npm install .:
0.458 E: Invalid value set for option Signed-By regarding source https://deb.nodesource.com/node_18.x/ nodistro (not a fingerprint)
0.458 E: The list of sources could not be read.
------
Dockerfile:13
--------------------
  12 |
  13 | >>> RUN apt-get update            && \
  14 | >>>     apt-get install -y nodejs && \
  15 | >>>     pip install -r requirements.txt && \
  16 | >>>     npm install .
  17 |
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get update            &&     apt-get install -y nodejs &&     pip install -r requirements.txt &&     npm install ." did not complete successfully: exit code: 100
ERROR: Service 'dev-tools' failed to build : Build failed
```
please see https://pad.pnpde.social/p/_srhy8QBL0hP5Dsy8IDG for a full log of all output

**To Reproduce**
1. Go to https://docs.joinbookwyrm.com/updating.html
2. Run the single steps of `bw-dev update`  as described

**Expected behavior**
no error

**Instance**
https://buecher.pnpde.social/

**Additional context**
Here's a full log of all output of the above command: https://pad.pnpde.social/p/_srhy8QBL0hP5Dsy8IDG

---

**Desktop (please complete the following information):**
    - OS: Ubuntu 22

**Comment by mouse-reeve** [comment] 2024-01-03 20:15
As a workaround while this is being fixed, you can skip building the dev tools image, which isn’t needed in production. I believe commenting out the apt-get node steps and then rerunning the update should work: https://github.com/bookwyrm-social/bookwyrm/blob/main/dev-tools/Dockerfile#L13

**Comment by nesges** [comment] 2024-01-03 22:08
Commenting out lines 13 to 16 helped with running `docker-compose build`, but the next step (`docker-compose run --rm web python manage.py migrate` failed with a new one:

```
root@oghma:/opt/bookwyrm# docker-compose run --rm web python manage.py migrate
Creating bookwyrm_web_run ... done
Operations to perform:
  Apply all migrations: admin, auth, bookwyrm, contenttypes, django_celery_beat, sessions
Running migrations:
  Applying bookwyrm.0184_auto_20231106_0421...Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column bookwyrm_notification.related_user_export_id does not exist
LINE 1: ...id", "bookwyrm_notification"."related_import_id", "bookwyrm_...
                                                             ^
```
(full output in https://pad.pnpde.social/p/-ZGs2VvXfvMzc2rBlUdW)

**Comment by mouse-reeve** [comment] 2024-01-03 22:49
Ah shoot I wrote a fix for that and merged it but forgot to add it to production. It should be working now

**Comment by nesges** [comment] 2024-01-03 22:53
Yepp, we're on 0.7.1 now :-D Thanks for all the love you pouring into Bookwyrm! <3

**Comment by dato** [comment] 2024-01-11 20:17
Hi!

Re:

> ```
> Invalid value set for option Signed-By: not a fingerprint
> ```

is it possible you had an old python 3.9 image, @nesges? The age of the image can be checked with `docker images`, for example I have:

```
$ docker images python:3.9
REPOSITORY   TAG       IMAGE ID       CREATED        SIZE
python       3.9       6c98275ba382   2 months ago   997MB
```

(I can only reproduce this problem if I go back in time, to `python:3.9-bullseye`.)

To anybody reading this, `docker pull python:3.9` should fix the problem, since it pulls the newer, bookworm-based image.

**Comment by nesges** [comment] 2024-01-11 23:26
Yeah, it's not new:
```
root@oghma:~# docker images python:3.9
REPOSITORY   TAG       IMAGE ID       CREATED         SIZE
python       3.9       850f8694d221   14 months ago   915MB
```

**Closed** 2024-01-17 23:31 UTC
Labels: bug
