### ISSUE TITLE
Initial Hashtag's # Removed, "#Tag" Becomes Merely "Tag"

### ISSUE THREAD

**Issue by varanasib** [bookwyrm-social/bookwyrm#2682] opened 2023-02-19 14:42 UTC
**Describe the bug**
When hashtags are added to a quote, the initial # mark does not appear on bookwyrm or when pushed to Mastodon.  On bookwyrm, adding a blank line between text and hashtags allows the initial # to appear on bookwyrm but not on Mastodon.

**To Reproduce**
1. Go to the book page
2. Click on Quote tab
3. Type in quote and add hashtags at conclusion

**Expected behavior**
The # before the initial hashtag should be preserved on bookwyrm and when pushed to mastodon

**Screenshots**
Screenshot from Mastodon.online attached.
![Untitled](https://user-images.githubusercontent.com/17454665/219955186-b54d7b72-175e-4d01-aa08-a768e9f041c7.png)

**Instance**
ramblingreaders.org

**Additional context**
Happens with other types of status posts, also

---

**Desktop (please complete the following information):**
    - OS: Linux LMDE
    - Browser Chrome

**Comment by varanasib** [comment] 2023-02-19 14:56
A workaround is to escape the initial # with \.  This allows the initial # and makes the hashtag a hashtag.

**Comment by chdorner** [comment] 2023-02-19 15:00
This is a duplicate of #2112. Good news is that proper hashtag support, both on BookWyrm and federated out to other ActivityPub services, is in the works and initial support is waiting for review in #2524 🎉 
Once that's released and deployed on the instance you use, then those hashtags will be properly linked on Mastodon as well (to the hashtag page on your Mastodon instance)

**Closed by chdorner** 2023-02-19 15:00 UTC
Labels: bug

**Comment by varanasib** [comment] 2023-02-19 15:04
Sorry for the duplicate.  My search powers are apparently rotten.

**Comment by chdorner** [comment] 2023-02-19 15:23
All good no worries 🙂 had these two fresh in mind because I just finished off the hashtag changes
