### ISSUE TITLE
New User Experience: Uploading .png profile picture causes server error

### ISSUE THREAD

**Issue by auntiviris** [bookwyrm-social/bookwyrm#2729] opened 2023-03-10 17:48 UTC

**Comment by mouse-reeve** [comment] 2023-03-11 00:04
I've heard from folks that uploading cover images isn't working as well, which may have the same root cause

**Comment by mouse-reeve** [comment] 2023-03-11 00:11
Thank you for reporting! I'm closing this as a duplicate of #2730

**Closed by mouse-reeve** 2023-03-11 00:11 UTC
