### ISSUE TITLE
Misparsing of `[...]` elisions

### ISSUE THREAD

**Issue by quisquous** [bookwyrm-social/bookwyrm#2993] opened 2023-09-13 20:17 UTC
**Describe the bug**

See: https://books.theunseen.city/user/picklish/review/99025/s/rosehouse

I made a post that says `> “Maritza, are you a person or are you the China Lake Precinct? The distinction is significant.” [...]` and the rendered output has `[..].` instead of `[...]` 

If I post this as a direct message, all of these also appear to be parsed incorrectly as well.
```
[...]

> [...]

>> [...]

> [...]
> other stuff
```

**To Reproduce**
Post `[...]` in a review/message.

**Expected behavior**
It should say `[...]` and not `[..].`

**Screenshots**
See: https://books.theunseen.city/user/picklish/review/99025/s/rosehouse

**Instance**
See: https://books.theunseen.city/

**Comment by hughrun** [comment] 2023-09-13 21:56
How odd!

Looks like this is coming from `format_links` in `views.status.py`:

```python
wrapped = _wrapped(potential_link) # <== _wrapped is True because the line is wrapped in "[]"
if wrapped:
    wrapper_close = potential_link[-1] # <== "]"
    formatted_content += potential_link[0] # <== "["
    potential_link = potential_link[1:-1] # <== "..."

ends_with_punctuation = _ends_with_punctuation(potential_link) # <== this is now True because the "potential link" ends in "."
if ends_with_punctuation:
    punctuation_glyph = potential_link[-1] # <== "."
    potential_link = potential_link[0:-1] # <== ".."

try:
    # raises an error on anything that's not a valid link
    validator(potential_link) # <== this will raise an exception since it's not a link

   ...

except (ValidationError, UnicodeError):
    formatted_content += potential_link # <== "[.."

if wrapped:
    formatted_content += wrapper_close # <== "[..]"

if ends_with_punctuation:
    formatted_content += punctuation_glyph # <== Oh no! ends_with_punctuation is True, so this becomes "[..]."
```

So the correct solution is for us to fix this function. In the short term, I would expect that if you added a space before the closing square bracket that would _probably_ render it as intended.

**Closed** 2023-11-05 22:42 UTC
Labels: bug
