### ISSUE TITLE
Bookwyrm Posts Not Showing on Mastodon Feed

### ISSUE THREAD

**Issue by pnutbutterprincess** [bookwyrm-social/bookwyrm#2626] opened 2023-01-27 01:10 UTC
Describe the bug
My updates on bookwyrm are not showing up in my home timeline on mastodon (I am following my bookwyrm account)

To Reproduce

- Already following a bookwyrm account from mastodon, make a post on bookwyrm (in this case, a comment)
- Check home timeline on mastodon account
- Check the profile of the bookwyrm account on mastodon (confirmed I am following)
- No updates are shown

Expected behavior
I expected to see the posts starting to show up in my feed once I had followed (thanks to [this issue being resolved](https://github.com/bookwyrm-social/bookwyrm/pull/2613)) ♥

Instance
bookwyrm.social

Additional context

- my mastodon account is on kolektiva.social, meaning I was unable to follow until recently once the above issue was resolved
- I am still pretty new to federation and mastodon, as well as bookwyrm, so hoping I understand the way they should work together correctly

**Comment by mouse-reeve** [comment] 2023-01-27 02:10
Thank you for reporting! The fix you linked has been merged, but it hasn't been deployed yet, so it will probably not be until next week that it's live. There are also still some pretty big delays in federating bookwyrm content from bookwyrm.social out, which I'm working on separately.

**Comment by pnutbutterprincess** [comment] 2023-01-27 02:46
Awesome, thank you! I went through the issues, but hadn't seen it. I appreciate the quick reply!

**Comment by alopix** [comment] 2023-01-27 15:09
This is exactly what I have been experiencing. It seems like posts are delayed by 6 days since I have seen a few of my bookwyrm.social reviews and states being published this week with always a 6 day delay.

**Comment by cloo** [comment] 2023-02-06 17:02
My post is already lagging more than a week to propagate to Mastodon, I suspect it will not show up.

**Comment by bluebirch** [comment] 2023-02-08 08:32
I can search individal posts from Mastodon, but if I favourite of boost, notifications doesn't reach back to BookWyrm.

**Comment by BlindMoon38** [comment] 2023-02-09 03:44
> My post is already lagging more than a week to propagate to Mastodon, I suspect it will not show up.

I got an update propagated after 12 days to Mastodon (Hometown), and interactions from Mastodon were retrieved and relayed to me after 18 days...

I can say with certainty that the problem is getting worse.

**Comment by genebean** [comment] 2023-02-10 05:00
> There are also still some pretty big delays in federating bookwyrm content from bookwyrm.social out, which I'm working on separately.
Is there somewhere in particular this is talked about? I’d like to track progress and see if I have any ability to help.

**Comment by mouse-reeve** [comment] 2023-02-20 21:33
@genebean this is the place!

**Comment by WesleyAC** [comment] 2023-03-21 01:41
This should be significantly better now, due to a combination of #2685 and having added more celery workers on the bookwyrm.social instance. I believe that the backlog of federation-related events has been entirely processed, and the queues are in a much better state now. I'm currently seeing messages federate within a minute or so.

I'm going to go ahead and close this, but please do open a new issue if you see any federation delays in the future.

**Closed by WesleyAC** 2023-03-21 01:41 UTC
