### ISSUE TITLE
Can't connect to bookwyrm.social - 504 Gateway Time-out

### ISSUE THREAD

**Issue by Llaverac** [bookwyrm-social/bookwyrm#2351] opened 2022-11-11 22:52 UTC
When I go to bookwyrm.social (on desktop or on mobile), nothing seems to happen for a while, and then the page just displays "504 Gateway Time-out".

**Comment by mouse-reeve** [comment] 2022-11-15 20:05
I'm closing this as a duplicate of #2357, which has more discussion of how that's being mitigated. Thank you for reporting!

**Closed by mouse-reeve** 2022-11-15 20:05 UTC
Labels: bug
