### ISSUE TITLE
Lists lead to 502 error

### ISSUE THREAD

**Issue by SyndicatedPillbug** [bookwyrm-social/bookwyrm#2402] opened 2022-11-17 20:43 UTC
**Describe the bug**
When clicking on any list, or when trying to create a new list, a 502 bad gateway error occurs. I've tried multiple browsers, and this has happened on two completely different servers.

**To Reproduce**
1. Go to lists
2. Click on any list
wait for 5022 error to emerge.

**Expected behavior**
I expected to see the list of books.

**Screenshots**
![image](https://user-images.githubusercontent.com/88639173/202555199-f3c36d91-5d5a-42ea-8927-19195038500b.png)

**Instance**
On which BookWyrm instance did you encounter this problem.

- https://bookrastinating.com/
- https://books.theunseen.city/

---

**Desktop (please complete the following information):**
    - OS: Windows
    - Browser Brave, Edge, Chrome
    - Version v1.45.127 (Brave). All browsers updated to latest edition.

**Comment by mouse-reeve** [comment] 2022-11-17 20:57
Closing this as a duplicate of #2117 <3

**Closed by mouse-reeve** 2022-11-17 20:57 UTC
Labels: bug
