### ISSUE TITLE
Can't move server

### ISSUE THREAD

**Issue by TrevorMellon** [bookwyrm-social/bookwyrm#1237] opened 2021-08-01 18:45 UTC
Tried moving the docker server from a Manjaro based system to and Ubuntu:21.

Replicated all the volumes to disk and tested, worked on the Manjaro system. Moved everything to the new host, loads fine but when I go to login it gives me "500: Internal Server Error".

Thought it might be the secret key as it had a £ sign in it, so changed the locale from US to GB. Nada.
Moved back to the Manjaro system changed the secret key and it prompted for my password successfully.

Made sure the disk permissions were correct in the move also.

Not sure now how to move it now, suggestions welcome.

**Comment by mouse-reeve** [comment] 2021-08-02 00:18
Huh! Can you get more information on what kind of errors might be happening? When you can load the landing page but not log in, that may mean that celery isn't working. Is that image up and connected on the ubuntu server?

**Comment by TrevorMellon** [comment] 2021-08-02 10:27
I was watching the logs with "docker-compose up" nothing was reported apart from the "error 500".

All the images came up without a problem, I thought it might be a database issue but "bw-dev migrate" reports no problem connecting.

It's very mysterious.

**Comment by mouse-reeve** [comment] 2021-08-02 14:02
We need to figure out what the error actually is; when django has `DEBUG` set to false, it doesn't log out 500 errors to the docker logs. If emailing is working, you can set your server to send you the error reports by adding a line to your `bookwyrm/settings.py` file: `ADMINS=[("name", "your.email@email.com")]` (https://docs.djangoproject.com/en/3.2/howto/error-reporting/).

**Comment by mouse-reeve** [comment] 2021-08-02 14:10
If that isn't working, you can also try a few things from the python shell (`./bw-dev shell`) and see if you can replicate the error. Here's what I'd suggest:

``` python3
from bookwyrm import models, settings
from bookwyrm.views.inbox import activity_task
import redis

# try to load a user from the database
models.User.objects.first()

# try to connect to activitystreams redis
redis.Redis(host=settings.REDIS_ACTIVITY_HOST, port=settings.REDIS_ACTIVITY_PORT, db=0)

# try to connect to celery
activity_task.delay({})
```

**Comment by TrevorMellon** [comment] 2021-08-02 14:47
Email is not working but I'll try the shell and let you know

**Comment by TrevorMellon** [comment] 2021-08-02 14:56
ok getting closer.

activity_task.delay() gives me:

"redis.exceptions.ResponseError: WRONGPASS invalid username-password pair or user is disabled."

**Comment by mouse-reeve** [comment] 2021-08-02 15:05
Okay great! That means that django is having a problem connecting to the celery broker. We need to figure out if the problem is that the username and password pair is incorrect, or disabled. Make sure that you're on the `production` branch, and your `.env` file has the correct password set for the redis broker. Then let's try to authenticate your redis broker:

`docker-compose exec redis_broker redis-cli AUTH <your redis password>`

That should tell you if authentication is disabled or the password is incorrect.

**Comment by TrevorMellon** [comment] 2021-08-02 15:07
docker-compose exec redis_broker redis-cli AUTH <your redis password>:

returns

OK

looks like it's right :)

**Comment by TrevorMellon** [comment] 2021-08-02 15:08
I'm on the production branch by the way

**Comment by mouse-reeve** [comment] 2021-08-02 15:14
Alright, sounds like redis is configured correctly and the problem is probably in django. In the django python shell, let's see if it knows the password. Try in `./bw-dev shell`:

``` python3
from bookwyrm import settings
print(settings.CELERY_BROKER)
```

If everything is configured correctly, the result should look like:
`redis://:<your redis broker password>:6379/0`

Folks in the past have run into problems with special characters being encoded incorrectly when translated between the .env file and the images, but that should have been resolved by https://github.com/bookwyrm-social/bookwyrm/pull/1157

**Comment by TrevorMellon** [comment] 2021-08-02 15:19
I was using an ascii token for the broker password, returned it perfectly.

However I was using a GB charset for the SECRET_KEY, only thing that didn't import well until I changed locale.
But we are close I can feel it ;)

**Comment by mouse-reeve** [comment] 2021-08-02 15:27
Hm, that does suggest that it could be a character encoding issue. Can you try changing the redis password?

**Comment by TrevorMellon** [comment] 2021-08-02 15:34
Changed the password and verified, password changed correctly, all ascii.

Ran the previous snippet for activity_task, same result:

kombu.exceptions.OperationalError: WRONGPASS invalid username-password pair or user is disabled.

**Comment by mouse-reeve** [comment] 2021-08-02 15:38
have you restarted the web image? `docker-compose restart web`

**Comment by mouse-reeve** [comment] 2021-08-02 15:38
maybe also the celery image: `docker-compose restart celery_worker`

**Comment by TrevorMellon** [comment] 2021-08-02 15:43
Just to be on the safe side, I repeated but I tend to "docker-compose down" every time

Same error

**Comment by mouse-reeve** [comment] 2021-08-02 15:46
I'm running out of ideas! I guess I'd try running `docker-compose build` and restart, but the fact that both django and redis are aware of the same password, but unable to connect is odd.

**Comment by TrevorMellon** [comment] 2021-08-02 15:50
Yeah I was at it all day yesterday, couldn't figure it out.

I've done the `docker-compose build --no-cache` several times.

It's not the end of the world if I can't move it but I think I'll try building on a virtual machine, it may help sanity check it.

I think it's a bug but not necessarily your bug.

**Comment by mouse-reeve** [comment] 2021-08-02 16:02
It's so frustrating to be stuck! But I'm run dry, thanks for being patient with this and please let me know if you figure anything out

**Comment by TrevorMellon** [comment] 2021-08-02 16:02
I will, thanks for all your time

**Comment by mouse-reeve** [comment] 2021-08-04 17:32
This occurred to me while debugging an unrelated celery issue - you could try checking the celery environment in flower. From the flower dashboard, which should be running on port 8888, if you click the worker name, then go to the config tab, it should show you all the environment variables. That'll show you if the correct values are set in the celery worker.

**Comment by TrevorMellon** [comment] 2021-08-04 18:02
I checked that, everything looks good but something is seriously wrong.

I decided to start fresh, maybe something on the filesystem was being messed up. So I did a git reset and pruned any volumes that may still exist. I did a build, `bw-dev initdb` and brought it up.

Created a user -> 500

Tried again, user exists, email exists

Tried to get it to reset the password -> 500

I'm using linode, have zero idea whats going wrong

**Comment by mouse-reeve** [comment] 2021-08-04 18:06
This is so bizarre! That's still consistent with a problem in which web can't connect to the celery_worker

**Comment by TrevorMellon** [comment] 2021-08-04 18:07
I can contact flower, do you want to take a look? I'll temporarily leave it open, passwords are temp anyway

**Comment by mouse-reeve** [comment] 2021-08-04 18:26
sure, what's the url?

**Comment by TrevorMellon** [comment] 2021-08-04 18:28
the server is at [bookwyrm.ignifi.me](https://bookwyrm.ignifi.me)

Flower can be viewed at [flower](https://bookwyrm.ignifi.me:8181)

**Comment by mouse-reeve** [comment] 2021-08-04 18:32
there's nothing that looks off there to me, unfortunately

**Comment by TrevorMellon** [comment] 2021-08-04 18:34
Yeah think it's a twilight zone episode ;)

It must be something about the host that's doing it

**Comment by mouse-reeve** [comment] 2021-08-04 18:37
can you check the version number for celery and redis?

**Comment by TrevorMellon** [comment] 2021-08-04 18:57
Redis server v=6.2.5 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=cc49a38120feeb6b

Celery: 4.4.2 (cliffs)

**Comment by mouse-reeve** [comment] 2021-08-04 19:31
I thought it might be a version mismatch issue, but bookwyrm.social is on redis 6.0.8 and the same celery version, so that doesn't seem super likely

**Comment by TrevorMellon** [comment] 2021-08-04 19:33
I think I'm grasping at straws

**Comment by IcedEagle** [comment] 2021-09-06 11:32
I think I'm running into this same issue... I didn't change machines though, just did some sort of mistake with the Docker config and now it's completely stuck in this state where it's always returning 500 and complaining about auth according to the debug output. I followed along with the above conversation, and based on what I see above, I see similar successes and no clear failures.

What I did was:
1) Go to Docker-Compose.yml, and add a port section to the redis_activity. Put both internal and external ports to 6380 I believe, but I didn't pay super close attention. I may have kept internal port at 6379. 
2) In env, Changed the port used for the redis_activity
3) In env, Changed the passwords used for the redis activity and redis broker. I made them the same value to test an unrelated issue.
4) After those changes, ran docker-compose up -d to pick up the changes
5) Everything was now borked, and undoing the changes has no effect

Is it normal for the flower dashboard to show either the actual password, or ***'s depending on which config value it is?

![image](https://user-images.githubusercontent.com/934801/132210472-eb229e32-b9a4-4a03-8c0b-4259b77a9293.png)

@TrevorMellon by chance were you able to figure this out?

**Comment by TrevorMellon** [comment] 2021-09-06 12:48
Hey @IcedEagle , sorry been super busy moving house etc. Put it on the back burner. It's good to know I'm not an isolated case though,  hopefully @mouse-reeve can pull a rabbit from the hat :)

**Comment by mouse-reeve** [comment] 2021-09-06 13:55
oh no! I don't have any rabbits springing to mind. If you haven't already, @IcedEagle, try stopping the containers, and then running `docker-compose up -d --build` -- sometimes I run into issues where images don't probably pick up changed to `.env`.

I'm having an issue on b.s where the certbot image is executing a command that was removed from docker-compose ages ago, so it's docker oddness all around 🤔

**Comment by IcedEagle** [comment] 2021-09-07 07:59
@mouse-reeve Yayyy thank you for the help! @TrevorMellon not sure if this will help, but our situations sounded similar enough that maybe this will help you as well.

I stopped all the containers, followed by running `docker-compose up -d --build`, and that exposed some issue that never showed up yesterday, maybe because I accidentally just did a git checkout from main instead of production branch. Running that command did make Docker do something different for sure. Due to this issue I couldn't understand at first, I spent some time stopping containers, deleting their images, doing another up docker-compose -d --build, etc. Either way, once I noticed what I did, I made sure to do a re-git of the Production branch, and then another set of `docker-compose up -d --build` and I was golden again.

Docker oddness indeed! Thank you for letting me know about that command. Back to reading! :)

**Comment by TrevorMellon** [comment] 2021-09-07 09:38
That's great @IcedEagle I will try that tonight :)

**Comment by TrevorMellon** [comment] 2021-09-14 09:15
Hey @mouse-reeve I finally got it working. I created a new host using Ubuntu 20.04 and had absolutely no problems. It seems to be an issue with Ubuntu 21 but doesn't matter, got there in the end :)

**Comment by mouse-reeve** [comment] 2021-09-14 14:38
Whew! Good to know for the future I guess

**Closed by mouse-reeve** 2021-09-14 14:38 UTC
Labels: bug, deployment
